apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "feast.core.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast.name" . }}
    component: core
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config: |
{{ toYaml core.config | indent 4 }}