apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "feast-serving.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast-serving.name" . }}
    component: serving
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "feast-serving.name" . }}
      component: serving
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "feast-serving.name" . }}
        component: serving
        release: {{ .Release.Name }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - name: {{ template "feast-serving.name" . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.grpc.targetPort }}
            name: grpc
          - containerPort: {{ .Values.service.http.targetPort }}
            name: http
        {{- if .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.service.http.targetPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{ end }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.http.targetPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
          {{- if .Values.resources.limits }}
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          {{- end }}
        env:
        {{- if .Values.serviceAccount }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcloud/service-accounts/{{ .Values.serviceAccount.key }}
        {{- end }}
        - name: CONFIG_PATH
          value: /etc/feast/config.yaml
        volumeMounts:
        - name: feast-serving-config
          mountPath: /etc/feast/config.yaml
          subPath: config.yaml
        - name: feast-serving-store-config
          mountPath: /etc/feast/store.yaml
          subPath: store.yaml
        {{- if .Values.serviceAccount }}
        - name: "{{ .Values.serviceAccount.name }}"
          mountPath: "/etc/gcloud/service-accounts"
          readOnly: true
        {{- end }}
      volumes:
      - name: feast-serving-config
        configMap:
          name:  {{ template "feast-serving.fullname" . }}
      - name: feast-serving-store-config
        configMap:
          name:  {{ template "feast-serving.fullname" . }}-store-config
      {{- if .Values.serviceAccount }}
      - name: "{{ .Values.serviceAccount.name }}"
        secret:
          secretName: "{{ .Values.serviceAccount.name }}"
      {{- end }}
