# replicaCount -- Number of pods that will be created
replicaCount: 1

image:
  # image.repository -- Docker image repository
  repository: gcr.io/kf-feast/feast-jupyter
  # image.tag -- Image tag
  tag: latest
  # image.pullPolicy -- Image pull policy
  pullPolicy: Always