name: linter

on: [push, pull_request]

jobs:
  lint-python:
    container: gcr.io/kf-feast/feast-ci:latest
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make install-python-ci-dependencies
      - name: Compile protos
        run: make compile-protos-python
      - name: Lint python
        run: make lint-python

  lint-go:
    container: gcr.io/kf-feast/feast-ci:latest
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make install-go-ci-dependencies
      - name: Lint go
        run: make lint-go